import { TopicData } from "@/lib/types/topic";

export const comentarioDanielProblemaLogico: TopicData = {
  slug: "problema-logico-livre-arbitrio",
  title: "Parte 2 — O Problema Lógico do Mal",
  subtitle: "A defesa do livre-arbítrio de Plantinga e a racionalidade da crença",
  categorySlug: "comentario-daniel",
  accent: "#94a3b8",
  status: "em-construcao",
  intro:
    "Continuando os comentários sobre o problema do mal: a versão lógica do problema, a defesa do livre-arbítrio de Alvin Plantinga e uma analogia para responder à acusação de que crer em Deus sem saber suas razões seria irracional.",
  sections: [
    {
      heading: "O problema lógico do mal: a defesa do livre-arbítrio de Plantinga",
      body: "Vamos nos ater inicialmente à parte lógica do problema do mal, utilizando a defesa de Plantinga do livre-arbítrio. Deus, quando criou a humanidade, a dotou de livre-arbítrio — a capacidade de realizar ações morais. Dado que Deus deseja se relacionar com a humanidade, o homem precisa ser livre para que um relacionamento com Deus seja algo verdadeiro e genuíno; se o homem não possui liberdade, então ele seria apenas um robô pré-programado para executar, e não um ser dotado de vontade própria. Alguns ateus se perguntam, a partir disso, se Deus não poderia criar um mundo com seres moralmente livres, mas sem a possibilidade de realizar o mal moral. Ora, não se trata de incapacidade da parte de Deus — realizar isso é intrinsecamente contraditório. Um ser que é livre, por definição, pode exercer escolhas morais; sendo assim, se o homem não pode escolher o mal, então ele não é livre. Argumentar que Deus é incapaz por não conseguir fazer isso é como dizer que Deus é incapaz por não criar um solteiro casado ou um quadrado redondo — a própria afirmação já é um erro semântico, simplesmente contraditória. Portanto, para que o homem possa ser verdadeiramente livre, é necessário que exista essa possibilidade de mal em frente a um bem maior. Isso é minimamente lógico o suficiente para responder ao paradoxo de Epicuro. Formalmente, porém, Plantinga não afirma isso como verdade, apenas como possibilidade lógica — essa é a diferença entre defesa e teodiceia. Ele propõe a proposição R: 'toda essência livre criada por Deus usaria mal seu livre-arbítrio em pelo menos uma circunstância' — a chamada depravação transmundial. Se é logicamente possível que R seja verdadeira, então é logicamente possível que nem Deus, sendo onipotente, conseguisse criar um mundo com bem moral genuíno sem também ter algum mal moral, porque a própria natureza da liberdade exige a possibilidade real de errar. R não precisa ser provada nem plausível; só precisa ser possível, e isso já basta para quebrar a alegação de contradição lógica de Mackie. Isso resolve o mal moral. Para o mal natural, Plantinga propõe algo parecido — a proposição R': é logicamente possível que o mal natural (terremotos, doenças) venha da atividade livre de agentes não humanos e sobrenaturais, como demônios. De novo, não precisa ser verdade, só precisa ser logicamente possível, o que já é suficiente para o objetivo da defesa.",
    },
    {
      heading: "A analogia do cortador de grama",
      body: "O ateu pergunta a um cristão, a partir da visão do problema do mal: 'por que Deus permite esses males específicos?' O teísta honestamente responde: 'eu não sei'. Assim, o ateu conclui que essa ignorância, por si só, já torna a crença em Deus irracional ou irrazoável. Mas será que essa intuição está realmente correta? Vejamos um exemplo simples do cotidiano: um pai de família chamado Paulo decide cortar a grama de sua casa, vai para o jardim e começa a cortar a grama. Observamos aqui duas coisas: primeiro, existe uma decisão mental que ocorre antes da ação — 'vou cortar a grama'; segundo, existe uma ação física — músculos se movendo, pernas andando, mão pegando o cortador e realizando todos os movimentos necessários. Mas, se perguntarmos, dentro dessa conexão de eventos, como exatamente a decisão mental de cortar a grama impulsionou os movimentos físicos do corpo para ir cortar a grama, simplesmente não sabemos explicar isso de forma totalmente precisa — e, quando digo preciso, me refiro a explicar a cadeia exata entre o pensamento e o movimento físico. Mas, convenhamos: por mais que não saibamos exatamente como se dá essa conexão, será que é lúcido dizer 'é irracional a conexão entre a decisão de Paulo de cortar a grama e o fato de ele estar cortando a grama neste exato momento, isso simplesmente não existe'? Claro que não. Por mais que não saibamos explicar o mecanismo neurológico, a conexão entre o pensamento consciente e o movimento físico continua sendo óbvia. Agora, dentro dessa analogia, vamos substituir os personagens: os teístas acreditam que Deus tem boas razões para permitir esse mal, enquanto os ateus dizem que essa ignorância é irracional. Ora, em ambos os casos existe uma ignorância sobre o mecanismo exato — 'como a decisão de Paulo causou precisamente o movimento' e 'qual é a razão de Deus' —, mas isso não significa automaticamente que acreditar na conexão decisão-ação de Paulo e na conexão Deus-razão seja irracional. Sendo assim, o ateu precisaria demonstrar que é improvável ou impossível existir uma razão para a existência desses males, mostrando alguma incongruência, contradição ou incapacidade da parte de Deus.",
    },
  ],
  relatedSlugs: ["introducao-epicuro", "problema-evidencial-teismo-cetico", "traducao-tooley"],
};
