import { TopicData } from "@/lib/types/topic";

export const inglesVocabularioGeral: TopicData = {
  slug: "vocabulario-geral",
  title: "Lugares e vocabulário geral",
  subtitle: "Lugares, substantivos, adjetivos, pronomes e conectores soltos",
  categorySlug: "ingles",
  accent: "#f472b6",
  status: "em-construcao",
  intro:
    "Palavras que não são verbos nem expressões inteiras — lugares, substantivos, adjetivos, pronomes e conectores que vou encontrando na leitura e anotando por aqui.",
  sections: [
    {
      heading: "Lugares",
      body: "Palavras que se referem a lugares.",
      vocabList: [
        { term: "loo", translation: "banheiro", note: "Gíria britânica." },
        { term: "lecture hall", translation: "sala de aula / diretório" },
        { term: "garden", translation: "jardim" },
      ],
    },
    {
      heading: "Palavras gerais",
      body: "Substantivos, adjetivos, pronomes e conectores soltos.",
      vocabList: [
        { term: "though", translation: "embora", note: "Em início de frase, funciona como 'embora'." },
        { term: "kind", translation: "espécie, raça ou tipo" },
        { term: "those", translation: "aqueles / aquelas", note: "Retorna algo já mencionado." },
        { term: "mighty", translation: "poderoso / majestoso" },
        { term: "loo roll", translation: "papel higiênico" },
        { term: "plumbing", translation: "encanamento" },
        { term: "nothing but", translation: "nada além de / somente" },
        { term: "headmistress", translation: "diretora" },
        { term: "headmaster", translation: "diretor" },
        {
          term: "myself",
          translation: "eu mesmo",
          note: "Usado pra indicar você mesmo dentro de uma frase. Ex.: students like myself and Gabriel = estudantes como eu e Gabriel; I did it myself = eu mesmo fiz isso.",
        },
        { term: "duties", translation: "deveres, funções ou obrigações" },
        { term: "sincere", translation: "sincero" },
        { term: "sincerest", translation: "o mais sincero" },
        { term: "spring", translation: "primavera" },
        { term: "as for", translation: "com relação a / quanto a" },
        { term: "aforementioned", translation: "mencionado anteriormente" },
        { term: "now that", translation: "agora que" },
        { term: "nearly", translation: "quase" },
        { term: "lunch", translation: "almoço" },
        { term: "dinner", translation: "janta" },
        { term: "meal", translation: "refeição" },
        { term: "till", translation: "até", note: "Mesma coisa que until, porém mais informal e comum." },
        { term: "schedule", translation: "agenda" },
        { term: "mistress", translation: "mestra" },
        { term: "threats", translation: "ameaças" },
        { term: "as such", translation: "sendo assim, portanto" },
        { term: "each", translation: "cada" },
        { term: "with no", translation: "sem" },
        { term: "current", translation: "atual" },
        { term: "leadership", translation: "liderança" },
        { term: "trouble", translation: "problema" },
        { term: "in fact", translation: "de fato" },
        { term: "bold", translation: "ousado / corajoso / atrevido" },
        { term: "fairy", translation: "fada" },
        {
          term: "between",
          translation: "entre",
          note: "Usado num grupo de 2 pessoas — diferente de among, usado quando o grupo tem 3 ou mais.",
        },
        {
          term: "among",
          translation: "entre",
          note: "Usado quando o grupo tem 3 pessoas ou mais — diferente de between, usado num grupo de 2.",
        },
        { term: "shame", translation: "pena" },
        { term: "which is why", translation: "por isso que, razão pela qual" },
        { term: "my dear", translation: "minha querida" },
        {
          term: "that one",
          translation: "essa, esse",
          note: "Sentido de 'isso aí' — retorna algo específico já mencionado.",
        },
        { term: "after all", translation: "afinal, no final das contas" },
        { term: "cute", translation: "fofo" },
        { term: "dumb", translation: "burro, bobo" },
        { term: "weird", translation: "estranho" },
        { term: "wonderful", translation: "maravilhoso" },
        { term: "shining", translation: "brilhante" },
        { term: "queen", translation: "rainha" },
        { term: "laws", translation: "leis", note: "Ex.: the laws of physics = as leis da física." },
        { term: "in light of", translation: "à luz de, considerando" },
        { term: "what will hopefully be", translation: "o que espero que seja" },
        { term: "what it's about", translation: "sobre o que é? do que se trata?" },
        { term: "freshers", translation: "calouros (alunos do primeiro ano)", note: "Termo britânico." },
      ],
      expressions: [
        {
          phrase: "about / around",
          translation: "sobre / acerca de / cerca de",
          explanation: "About pode se traduzir como 'sobre', mas também pode ser usado em outros contextos, como 'cerca de'.",
          example: "I sleep about 7 hours.",
          exampleTranslation: "Eu durmo cerca de 7 horas.",
        },
        {
          phrase: "Therefore",
          translation: "portanto, por isso",
          example: "Therefore, I decided to study.",
          exampleTranslation: "Portanto, eu decidi estudar.",
        },
        {
          phrase: "Although",
          translation: "embora, apesar de",
          example: "Although it's late, I'll study.",
          exampleTranslation: "Embora esteja tarde, eu vou estudar.",
        },
        {
          phrase: "Throughout",
          translation: "ao longo de, por todo",
          example: "Throughout the day, I worked hard.",
          exampleTranslation: "Ao longo do dia eu trabalhei bastante.",
        },
        {
          phrase: "kinda / kind of",
          translation: "meio, tipo",
          example: "I think they are kinda cute.",
          exampleTranslation: "Eu acho eles meio fofos.",
        },
        {
          phrase: "a bunch of",
          translation: "um bando de, um grupo de",
          example: "A bunch of friends.",
          exampleTranslation: "Um bando de amigos.",
        },
        {
          phrase: "across",
          translation: "através de, ao longo de, do outro lado de",
          example: "Identity is created and maintained across cloud software accounts.",
          exampleTranslation: "Identidade é criada e mantida através de contas de software na nuvem.",
        },
        {
          phrase: "seamlessly",
          translation: "perfeitamente, sem falhas, sem emendas visíveis",
          explanation: "Literalmente 'sem costura' (seam = costura).",
          example: "The two pieces fit together seamlessly.",
          exampleTranslation: "As duas peças se encaixam perfeitamente.",
        },
        {
          phrase: "business",
          translation: "negócio, empresa",
          example: "I have my own business.",
          exampleTranslation: "Eu tenho meu próprio negócio.",
        },
      ],
    },
  ],
  relatedSlugs: ["verbos", "gramatica-if-only-superlativo"],
};
