import { TopicData } from "@/lib/types/topic";

export const inglesVerbos: TopicData = {
  slug: "verbos",
  title: "Verbos",
  subtitle: "Verbos que vou anotando ao longo das leituras e do estudo",
  categorySlug: "ingles",
  accent: "#f472b6",
  status: "em-construcao",
  intro:
    "Uma lista de verbos que fui juntando aos poucos, principalmente através de leitura (atualmente lendo Fate: A Saga Winx, em inglês). Não segue ordem de curso — vai crescendo conforme eu avanço.",
  sections: [
    {
      heading: "Verbos",
      body: "Verbos que fui anotando ao longo da leitura.",
      vocabList: [
        { term: "shall", translation: "significa a mesma coisa que will, porém num sentido mais formal" },
        { term: "ensured", translation: "garantido", note: "Passado de ensure (garantir)." },
        { term: "regret", translation: "arrepender-se" },
        { term: "hope", translation: "esperar / esperança" },
        { term: "rise again", translation: "erguer-se novamente" },
        {
          term: "yielded",
          translation: "rendeu, cedeu, produziu",
          note: "Passado de yield. Não confundir com wield (empunhar).",
        },
        {
          term: "running",
          translation: "correndo",
          note: "Também pode significar administrando ou dirigindo. Ex.: run a business = dirigir um negócio.",
        },
        { term: "appoint", translation: "nomear alguém para uma função" },
        { term: "appointed", translation: "nomeado" },
        { term: "take over", translation: "assumir o controle de algo", note: "Geralmente substituindo alguém ou algo." },
        { term: "hire", translation: "contratar", note: "hired = contratado." },
        { term: "doubt", translation: "duvido" },
        { term: "seem", translation: "parecer" },
        { term: "plan", translation: "planejar" },
        { term: "evolve", translation: "evoluir" },
        { term: "bear", translation: "aguentar, suportar" },
        { term: "offer", translation: "oferecer" },
        {
          term: "bring",
          translation: "trazer",
          note: "Traz o sentido de trazer em direção a quem fala — diferente de take, que tem o sentido de levar para longe.",
        },
        { term: "brought", translation: "trouxe", note: "Passado de bring (trazer)." },
        { term: "bring back", translation: "trazer de volta" },
        { term: "prod", translation: "cutucar / espetar" },
      ],
      expressions: [
        {
          phrase: "to last",
          translation: "durar",
          explanation: "Usado em contextos de duração.",
          example: "The movie lasted 2 hours.",
          exampleTranslation: "O filme durou 2 horas.",
        },
        {
          phrase: "make / made + verb",
          translation: "fazer alguém fazer ou sentir algo",
          explanation: "made é o passado de make. Quando make ou made vem acompanhado de outro verbo, não se usa 'to' antes desse verbo. Ex.: you make me laugh = você me faz rir; this song makes me happy = essa música me deixa feliz.",
          example: "She made him cry.",
          exampleTranslation: "Ela o fez chorar.",
        },
        {
          phrase: "falling for",
          translation: "cair em / se deixar enganar",
          explanation: "No sentido de cair numa conversa ou numa pegadinha.",
        },
        {
          phrase: "bring about",
          translation: "causar, provocar",
          example: "The new policy brought about many changes.",
          exampleTranslation: "A nova política causou muitas mudanças.",
        },
        {
          phrase: "pinch",
          translation: "beliscar",
          explanation: "Também pode ser substantivo: a pinch of salt = uma pitada de sal.",
          example: "Ouch! Don't pinch me.",
          exampleTranslation: "Ouu, não me belisque.",
        },
        {
          phrase: "feels",
          translation: "parece",
          explanation: "feel pode ter o sentido de 'parecer'.",
          example: "This feels weird.",
          exampleTranslation: "Isso parece estranho.",
        },
        {
          phrase: "unleash",
          translation: "soltar, liberar, libertar",
          explanation: "Sentido de liberar algo que estava contido ou preso. Pode ser usado de forma figurada, como liberação de poder.",
          example: "To unleash their value.",
          exampleTranslation: "Liberar seu valor.",
        },
        {
          phrase: "belies / belied",
          translation: "desmente, contradiz; revela algo diferente da aparência",
          explanation: "belied é o passado. Em contexto de software: an API's design belies much about the program behind it = o design de uma API revela muito sobre o programa por trás dela.",
          example: "His calm voice belied his anger.",
          exampleTranslation: "Sua voz calma desmentia / escondia sua raiva.",
        },
      ],
    },
  ],
  relatedSlugs: ["vocabulario-geral", "expressoes-girias"],
};
